- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation
       ansible_user: cloud-user
       ansible_ssh_private_key_file:  "/root/.ssh/openstack.pem"

- hosts: workstation
  become: yes
  roles:
    - osp-instance-delete
