- hosts: frontends
  gather_facts: false
  tasks:
  - name: Get status of haproxy
    command:
      systemctl status haproxy
    register: haproxy_status

  - name: Print haproxy status
    debug: msg="{{ haproxy_status }}"

  - name: Get haproxy logs
    command:
      journalctl -lu haproxy -o cat
    register: haproxy_logs
  - name: Print haproxy logs
    debug: msg="{{ haproxy_logs }}"

  - name: Get haproxy servers
    command:
      grep server  /etc/haproxy/haproxy.cfg
    register: haproxy_servers
  - name: Print haproxy servers
    debug: msg="{{ haproxy_servers }}"


- hosts: apps
  gather_facts: false
  tasks:
  - name: Check backend app on port 8080 
    uri:
      url: "http://{{ inventory_hostname }}:8080"
      return_content: yes
    register: webpage

  - name: Print backend result
    debug: msg="{{ webpage }}"




#DFW#
- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri:
      url: "http://{{ inventory_hostname }}"
      return_content: yes
    register: webpage

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.content"
    tags:
      - osp.smoke
