---
# vars file for osp.servers
osp_servers:
  - name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    floating_ip: 10.10.10.9
    security_group: frontend
    meta:
      - { group: frontends, deployment_name: QA}
  - name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    floating_ip: 10.10.10.13
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
  - name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    floating_ip: 10.10.10.6
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
  - name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    floating_ip: 10.10.10.16
    security_group: db
    meta:
      - { group: appdbs, deployment_name: QA}
