---
# tasks file for lb-tier
  - name: Install software with yum
    yum:
      name:
      - haproxy
      - python2-httpie
      state: latest
    when: three_tier_frontend_install_software and 'frontends' in group_names

#DFW#  - name: Configure OSP/QA haproxy
#DFW#    template:
#DFW#      src: haproxy.cfg.j2
#DFW#      dest: /etc/haproxy/haproxy.cfg
#DFW#    when: ansible_virtualization_type=='openstack'
#DFW#    notify: restart-haproxy
  
  - name: Print OSP/QA hostvars
    debug:
      msg: "{% for appsrv in groups[three_tier_frontend_app_group_name] %}
              {{ hostvars[appsrv] }}
             {% endfor %}"
    when: ansible_virtualization_type=='openstack' and 'frontends' in group_names

  - name: Print AWS/Prod hostvars
    debug:
      msg: "{% for appsrv in groups[three_tier_frontend_app_group_name] %}
              {{ hostvars[appsrv].ec2_tag_aws_cloudformation_logical_id }}
             {% endfor %}"
    when: ansible_virtualization_type!='openstack' and 'frontends' in group_names



  - name: Configure AWS/Prod haproxy
    template:
      src: haproxy.cfg_aws.j2
      dest: /etc/haproxy/haproxy.cfg
    when: ansible_virtualization_type!='openstack' and 'frontends' in group_names
    notify: restart-haproxy
  
  - name: Start and enable HAProxy
    service:
      name: haproxy
      state: started
      enabled: true


