---
# Tasks file for db-tier
# Deploy postgres
  - name: Install progress
    command: "yum install -y postgresql-server"

  #- name: Install postgres
  #  yum:
  #    name: postgresql-server
  #    state: latest

  - name: Enable postgresql at boot
    service:
      name: postgresql
      enabled: yes

  - name: Check pgsql data dir
    find: 
      paths: /var/lib/pgsql/data
      file_type: directory
      patterns: "*"
    register: pgsql_data_dir_res

  - name: Initilize postgres
    command: postgresql-setup initdb
    register: r_postgres_init
    failed_when: >-
      r_postgres_init.rc != 0 and
      r_postgres_init.stdout != 'Data directory is not empty!'
    when: pgsql_data_dir_res.matched|int == 0

  - name: Start postgres
    service:
      name: postgresql.service
      state: started

