---
# tasks file for base-config
- name: Common Configuration
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: enable repos
    copy:
      src: open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: u=rw,g=r,o=r
    when: three_tier_common_enable_repos


